[package]
name = "rus-ooc"
version = "0.1.0"
authors = ["Matthieu <matthieu.ospici@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"